apiversion: apps/v1
kind: Deployment
metadata:
  name: cardeployment
spec:
  matchLabels:
    app: car
  template:
   metadata:
      labels:
        app: car
   spec:
    containers:
    - image: devopschand/car
      ports:
      - containerPort: 80
----
apiVersion: v1
kind: Service
metadata:
   name: carservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
