apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardeploy 
spec:
  selector:
    matchLabels:
      app: car
  template:
    metadata:
      labels:
        app: car
    spec:
     containers:
     - name: carcontainer
       image: docker.io/devopschand/car:
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: carservice
spec:
  type: NodePort
  selector:
     app: car
  ports:
  - port: 80
    targetPort: 80
