apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardeploy
spec:
  selector:
    matchLabels:
      app: mm
  template:
    metadata:
      labels:
        app: mm
    spec:
     containers:
     - name: maintenance Page
       image: docker.io/devopschand/maintenance
       ports:
       - containerPort: 80
