apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenancedeploy
spec:
  selector:
    matchLabels:
      app: mm
  template:
    metadata:
      labels:
        app: mm
    spec:
     containers:
     - name: maintenancepage
       image: docker.io/devopschand/maintenance:IMAGE_TAG
       ports:
       - containerPort: 80
